config/routes.rb
Oceanic::Application.routes.draw do

  root :to => 'flights#index'

  resources :planes, :only => [:index, :new, :create] do
  end

  resources :flights, :only => [:index, :new, :create, :show] do
    collection do
      post "purchase"
      get 'search'
      post "destinations"
      post "search_flights"
    end
  end

  resources :users, :only => [:new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'


end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  destination :string(255)
#  origin      :string(255)
#  date        :date
#  plane_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Flight < ActiveRecord::Base
  attr_accessible :name, :destination, :origin, :date, :plane_id
  has_many :seats
  belongs_to :plane

  def create_seats
    num_seats = self.plane.aisles * self.plane.rows
    num_seats.times do |x|
      Seat.create(flight_id:self.id, plane_id:self.plane.id)
    end
  end
end

app/models/plane.rb
# == Schema Information
#
# Table name: planes
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  rows       :integer
#  aisles     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Plane < ActiveRecord::Base
  attr_accessible :name, :rows, :aisles
  has_many :flights
  has_many :seats
end

app/models/seat.rb
# == Schema Information
#
# Table name: seats
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  user_id    :integer
#  flight_id  :integer
#  plane_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  is_taken   :boolean          default(FALSE)
#

class Seat < ActiveRecord::Base
  attr_accessible :name, :user_id, :flight_id, :plane_id
  belongs_to :user
  belongs_to :flight
  belongs_to :plane
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  is_admin        :boolean          default(FALSE)
#  funfact         :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :name, :email, :password, :password_confirmation, :is_admin, :funfact
  has_many :seats

  def is_admin?
    self.is_admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate

  private
  def authenticate
    @auth = (session[:user_id].present?) ? User.find(session[:user_id]) : nil
  end
  def check_if_admin
    redirect_to(root_path) if @auth.nil? || !@auth.is_admin
  end
  def check_if_not_admin
    redirect_to(root_path) if @auth.is_admin
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_filter :check_if_admin, :only => [:new, :create]
  before_filter :check_if_not_admin, :only => [:purchase, :search]

  def index
    @flights = Flight.order(:date)
  end

  def new
    @flight = Flight.new
    @planes = Plane.all
  end

  def create
    @flight = Flight.create(params[:flight])
    @flight.plane = Plane.find(params[:plane])
    @flight.save
    @flight.create_seats
    @flights = Flight.order(:date)
  end

  def show
    @flight = Flight.find(params[:id])
  end

  def purchase
    seats = params[:ids]
    seats.each do |seat|
      s = Seat.find(seat.to_i)
      s.is_taken = true
      s.save
      @auth.seats << s
    end
    @flight = Flight.find(params[:fid])
  end

  def search
    @flights = Flight.all.map(&:origin).uniq.map{|origin| Flight.where(:origin => origin).first}
  end

  def destinations
    flight = Flight.find(params[:origin])
    @destinations = Flight.where(origin:flight.origin).map(&:destination).uniq.map{|destination| Flight.where(:origin => flight.origin, :destination => destination).first}
    @origin = flight
  end

  def search_flights
    origin = params[:origin]
    destination = Flight.find(params[:destination]).destination
    @flights = Flight.where(origin:origin, destination:destination).order(:date)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController

def index
  @planes = Plane.order(:name)
end

def new
  @plane = Plane.new
end

def create
  @plane = Plane.create(params[:plane])
  @planes = Plane.order(:name)
end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.where(:email => params[:email]).first
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      @flights = Flight.order(:date)
    else
      session[:user_id] = nil
    end
      authenticate
  end

  def destroy
    session[:user_id] = nil
    authenticate
    @flights = Flight.order(:date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(params[:user])
    @user.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_nav
    nav = ""
    nav += "<li>#{link_to('Home', flights_path, :class => 'button radius small alert')}</li>"

    if @auth.present? && @auth.is_admin?
      nav += "<li>#{link_to('Planes', planes_path, :class => 'button radius small alert')}<li>"
      nav += "<li>#{link_to('Flights', flights_path, :class => 'button radius small alert')}<li>"
    end
    if @auth.present?
      nav += "<li>#{link_to('Logout: ' + @auth.name, '/login', :method => :delete, :remote => true, :class => 'button radius small alert')}<li>"
    else
      nav += "<li>#{link_to('Register', new_user_path, :remote => true, :class => 'button radius small alert')}</li>"
      nav += "<li>#{link_to('Login', login_path, :remote => true, :class => 'button radius small alert')}</li>"
    end
  end
end

app/views/flights/_flights.html.haml
-if @auth.present? && (@auth.is_admin == true)
  #addflight
    =link_to('Add Flight', new_flight_path, :remote => true, :class => 'button radius small info')
-if @auth.present? && (@auth.is_admin == false)
  #searchflight
    =link_to('Search Flights', search_flights_path, :remote => true, :class => 'button radius small info')
#flight_form
  .row
    .small-4.small-centered.columns
      #origins
      #destinations
#flights
  %table#flight_table
    %tr
      %th Date
      %th Flight
      %th Origin => Destination
      %th Plane
      -if @auth.present? && (@auth.is_admin == true)
        %th Available Seats
    -@flights.each do |flight|
      %tr
        %td= flight.date
        %td= link_to(flight.name, flight_path(flight))
        %td= "#{flight.origin} => #{flight.destination}"
        %td= flight.plane.name
        -if @auth.present? && (@auth.is_admin == true)
          %td= flight.seats.select{|x| x.is_taken == false}.count

app/views/flights/_form.html.haml
.row
  .small-4.small-centered.columns
    = form_for @flight, :remote => true do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :date
      = f.text_field :date
      = f.label :origin
      = f.text_field :origin
      = f.label :destination
      = f.text_field :destination
      = f.label :plane
      = select_tag(:plane, options_from_collection_for_select(@planes, "id", "name"))
      = link_to('Cancel', '#', :'data-clear-form' => true, :class => 'button small radius alert form_button', :id => "cancel_create")
      = f.submit 'Create Flight', :class => 'button small radius info form_button'

app/views/flights/_in_session_show.html.haml
%h3= "Flight #{@flight.name}  /  #{@flight.date.strftime("%B %d, %Y")}"
%h4= "#{@flight.origin.upcase} to #{@flight.destination.upcase}"
#seat_plan
  = render :partial => 'seats'

app/views/flights/_out_session_show.html.haml
%h3 Log in to "purchase" seats on this flight

app/views/flights/_search.html.haml
= form_tag '/flights/destinations', :remote => true do |f|
  = label_tag :origin, 'Select origin:'
  = select_tag(:origin, options_from_collection_for_select(@flights, "id", "origin"), :prompt => "Please select an origin")
  / = link_to('Cancel', '#', :'data-clear-form' => true, :class => 'button tiny radius alert')
  / = submit_tag 'Search Destinations', :id => 'searchf', :class => 'button tiny radius success'

app/views/flights/_seats.html.haml
%h2#fid= @flight.id
%span.seats#num_available= "Seats available: #{@flight.seats.select{|x| x.is_taken == false}.count}"
%span.seats#num_taken= "Seats taken: #{@flight.seats.select{|x| x.is_taken == true}.count}"
.row
  .small-12.columns
    #show_flight_table
      %table
        - i=0
        - seats = @flight.seats.order(:id)
        %tr#tr
          %th
          -@flight.plane.rows.times do |row|
            %td= row+1
        -@flight.plane.aisles.times do |aisle|
          %tr
            %th#th= (aisle+65).chr
            -@flight.plane.rows.times do |row|
              %td
                -if seats[i].user.nil?
                  .available
                    = "Available"
                    = "#{(aisle+65).chr}#{row+1}"
                -else
                  .taken= "#{seats[i].user.name.split[0]}"
                %div.seatsids= seats[i].id
                -i+=1
        %tr#tr
          %th
          -@flight.plane.rows.times do |row|
            %td= row
    = button_to("Purchase","#", :id => "purchase_btn", :class => 'button tiny radius alert')

app/views/flights/create.js.erb
$('#flight_whole').empty().append('<%= j render(:partial => 'flights') %>');

app/views/flights/destinations.js.erb
$('#destinations').empty().append('<%=j render(:partial => 'search_destinations') %>');

app/views/flights/index.html.haml
.row
  .small-8.small.columns#flight_whole
    = render :partial => "flights"

app/views/flights/new.js.erb
$('#flight_form').empty().append('<%=j render(:partial => 'form') %>');

app/views/flights/purchase.js.erb
$("#seat_plan").empty().append("<%=j render :partial => 'seats' %>");

app/views/flights/search.js.erb
// if($("#origins").length == 0)
// {
//   $('#origins').empty().append('<%=j render(:partial => 'search') %>');
//   var origins = $("#origins")
//   $("#flight_form").append(origins);
// }
// else
// {
//   $('#origins').empty().append('<%=j render(:partial => 'search') %>');
// }

$('#origins').empty().append('<%=j render(:partial => 'search') %>');

app/views/flights/search_flights.js.erb
$("#flight_whole").empty().append("<%=j render :partial => 'flights' %>")

app/views/flights/show.html.haml
-if @auth.present?
  .flight_show_page
    %h3= "Flight #{@flight.name}  /  #{@flight.date.strftime("%B %d, %Y")}"
    %h4= "#{@flight.origin.upcase} to #{@flight.destination.upcase}"
    #seat_plan
      = render :partial => 'seats'
-else
  %h3 Log in to "purchase" seats on this flight

app/views/layouts/_body.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="row">
      <div class="small-4 columns small-offset-8">
        <div id="reg_form"></div>
      </div>
    </div>

    <%= yield %>

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns"><hr>
    <div class="row">
      <div class="large-6 columns">
        <p>&copy; 2013 Oceanic Airlines</p>
      </div>
      <div class="large-6 columns">
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="row">
  <div class="large-6 columns" id="logo_container">
    <img id="logo" alt="Oceanic_03" src="/assets/oceanic_03.png">
    <div class=headername>ceanic airlines </div>
  </div>
  <div class="large-6 columns" id="btn_group_container">
    <div class="nav-bar">
      <ul class="button-group">
        <li><%== login_nav %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Oceanic Airlines</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="//use.typekit.net/lxb8lov.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= favicon_link_tag 'plane.ico' %>
</head>
<body>
  <div id='nav'><%= render :partial => 'layouts/nav' %></div>
  <div class="row">
    <div class="small-12 columns" id="container">
<!--       <div id='nav'><%= render :partial => 'layouts/nav' %></div> -->
      <div id='body'><%= render :partial => 'layouts/body' %></div>

    </div>
  </div>
  <div id='footer'><%= render :partial => 'layouts/footer' %></div>


  <script>
  $(document).foundation();
  </script>
</body>
</html>

app/views/planes/_form.html.haml
= form_for @plane, :remote => true do |f|
  = f.label :name
  = f.text_field :name, :autofocus => true
  = f.label :rows
  = f.number_field :rows
  = f.label :aisles
  = f.number_field :aisles
  = link_to('Cancel', '#', :'data-clear-form' => true, :class => 'button small radius alert form_button')
  = f.submit 'Create Plane', :class => 'button small radius info form_button'

app/views/planes/_planes.html.haml
%h4= @plane.name
#plane_box
  / .row
  /   -@plane.aisles.times do |aisle|
  /     / -if @plane.rows > 12
  /     .small-1.columns
  /       -@plane.rows.times do |row|
  /         .row
  /           .seat= "#{(aisle+65).chr}#{row+1}"
  /   %div{:class => "small-#{12-@plane.aisles} columns"}
  .row
    .small-12.columns
      %table
        %tr#tr2
          %th
          -@plane.rows.times do |row|
            %td= row+1
        -@plane.aisles.times do |aisle|
          %tr
            %th#th2= (aisle+65).chr
            -@plane.rows.times do |row|
              %td= "#{(aisle+65).chr}#{row+1}"
        %tr#tr2
          %th
          -@plane.rows.times do |row|
            %td= row

    //Aisles correspond to columns. so 3 aisles and foundations shows 3 colmn div. another 9 column div creates. w/in your 3-column div, in each column you have a row, which corresponds to a seat.
    //thus you get the seat (which is its own div w/ class .seat) labeled.

app/views/planes/_planes_list.html.haml
-@planes.each do |plane|
  .row
    .small-12.columns
      %h3= plane.name
  .row
    .small-11.small-offset-1.columns
      %h5= "Rows: #{plane.rows}"
      %h5= "Aisles: #{plane.aisles}"
      %h5= "Total Seats: #{plane.rows * plane.aisles}"

app/views/planes/create.js.erb
$('#plane').empty().append('<%= j render(:partial => 'planes') %>');
$("#plane_form").empty();
$('#plane_list').empty().append('<%= j render(:partial => 'planes_list') %>');

app/views/planes/index.html.haml
.row
  .small-4.columns
    #addplane
      =link_to('Add Plane', new_plane_path, :remote => true, :class => 'button small radius info')
.row
  .small-4.small-centered.columns
    #plane_form
.row
  .small-12.columns
    #plane
.row
  .small-6.small-offset-1.columns
    #plane_list
      = render :partial => 'planes_list'

app/views/planes/new.js.erb
$('#plane_form').empty().append('<%=j render(:partial => 'form') %>');
$("#addplane").hide();

app/views/session/_form.html.haml
= form_tag '/login', :remote => true do
  = label_tag :email
  = text_field_tag :email, nil, :autofocus => true
  = label_tag :password
  = password_field_tag :password
  = link_to('Cancel', '#', :'data-clear-form' => true, :class => 'button radius tiny alert')
  = submit_tag 'Get LOST', :class => 'button tiny radius info'

app/views/session/create.js.erb
<% if @auth.present? %>
  $('#nav').empty();
  $('#nav').append('<%=j render :partial => 'layouts/nav' %>');
  $('#flight_whole').empty().append('<%= j render(:partial => 'flights/flights') %>');
  $('#reg_form').hide("fold", 1000);
<% else %>
  $('#reg_form').effect("bounce", 300)
<% end %>

app/views/session/destroy.js.erb
$('#login_form').empty();
$('#nav').empty();
$('#nav').append('<%=j render :partial => 'layouts/nav' %>')
$('#flight_whole').empty().append('<%= j render(:partial => 'flights/flights') %>');

app/views/session/new.js.erb
$('#reg_form').empty().append('<%=j render(:partial => 'form') %>').show("fold", 500);

app/views/users/_form.html.haml
= form_for @user, :remote => true do |f|
  = f.label :name
  = f.text_field :name, :autofocus => true
  = f.label :email
  = f.text_field :email
  = f.label :funfact, 'Fun Fact'
  = f.text_field :funfact
  = f.label :password
  = f.password_field :password
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  = link_to('Cancel', '#', :'data-clear-form' => true, :class => 'button small radius alert')
  = f.submit 'Create Account', :class => 'button radius small info'

app/views/users/create.js.erb
<% if @user.valid? %>
  $('#reg_form').effect("fold", 1000);
  $('#nav').empty();
  $('#nav').append('<%=j render :partial => 'layouts/nav' %>')
<% else %>
  $('#reg_form').effect("bounce", 300);
<% end %>

app/views/users/new.js.erb
$('#reg_form').empty().append('<%=j render(:partial => 'form') %>').show("fold", 500);